<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\NovaPasta\" />
    <Folder Include="Forms\" />
    <Folder Include="Helpers\" />
    <Folder Include="UserControls\" />
    <Folder Include="Themes\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>