<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\images\logo\logo\**" />
    <Content Remove="wwwroot\images\logo\logo\**" />
    <EmbeddedResource Remove="wwwroot\images\logo\logo\**" />
    <None Remove="wwwroot\images\logo\logo\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AtelieDosPontinhos.Application\AtelieDosPontinhos.Application.csproj" />
    <ProjectReference Include="..\AtelieDosPontinhos.Infrastructure\AtelieDosPontinhos.Infrastructure.csproj" />
  </ItemGroup>

</Project>
